# Generated by Django 4.0.2 on 2022-05-03 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=50)),
                ('account_discount', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_cost', models.IntegerField()),
                ('number_of_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('club_guid', models.UUIDField(default=uuid.uuid4)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.address')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('age_rating', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('film_description', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField()),
                ('last_logged_in', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField(unique=True)),
                ('screen_seats_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('unique_number', models.UUIDField(default=uuid.uuid4)),
                ('unique_password', models.CharField(max_length=50)),
                ('login_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.loginaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.account')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.booking')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.club')),
            ],
        ),
        migrations.CreateModel(
            name='GuessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.booking')),
                ('card_details', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='films.carddetails')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='club_rep',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='films.representative'),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.contactdetails'),
        ),
        migrations.CreateModel(
            name='BookedTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.booking')),
                ('screen_showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.showing')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.loginaccount')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.roles')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='card_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.carddetails'),
        ),
    ]
