# Generated by Django 4.0.2 on 2022-05-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='screen_seats_number',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='screen_number',
            new_name='number',
        ),
    ]
