# Generated by Django 4.0.2 on 2022-05-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('films', '0002_rename_screen_seats_number_screen_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='address',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_rep',
        ),
        migrations.RemoveField(
            model_name='club',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='login_account',
        ),
        migrations.AlterField(
            model_name='logintransaction',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.club'),
        ),
        migrations.DeleteModel(
            name='AccountRole',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.DeleteModel(
            name='LoginAccount',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
