# Generated by Django 4.0.2 on 2022-03-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_age_rating_alter_film_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.booking')),
                ('card_details_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='films.carddetails')),
            ],
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='LoginTransaction',
        ),
        migrations.RemoveField(
            model_name='screenshowings',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='screenshowings',
            name='showing_id',
        ),
        migrations.AddField(
            model_name='club',
            name='club_rep',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='films.representative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='showings_id',
            field=models.ManyToManyField(blank=True, to='films.Showing'),
        ),
        migrations.DeleteModel(
            name='ClubRepresentative',
        ),
        migrations.DeleteModel(
            name='ScreenShowings',
        ),
    ]
