# Generated by Django 4.0.2 on 2022-05-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_club_address_remove_club_club_rep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtickets',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookedtickets',
            name='screen_showing',
        ),
        migrations.RemoveField(
            model_name='bookedtickets',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='guesstransaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='guesstransaction',
            name='card_details',
        ),
        migrations.RemoveField(
            model_name='logintransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='logintransaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='logintransaction',
            name='club',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='BookedTickets',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CardDetails',
        ),
        migrations.DeleteModel(
            name='GuessTransaction',
        ),
        migrations.DeleteModel(
            name='LoginTransaction',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
