# Generated by Django 4.0.2 on 2022-05-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_bookedtickets_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='capacity',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
