# Generated by Django 4.0.2 on 2022-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_showing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_number',
            field=models.IntegerField(unique=True),
        ),
    ]
