# Generated by Django 4.0.2 on 2022-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_screen_screen_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='card_details_id',
            new_name='card_details',
        ),
        migrations.RenameField(
            model_name='accountrole',
            old_name='login_account_id',
            new_name='login_account',
        ),
        migrations.RenameField(
            model_name='accountrole',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='bookedtickets',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='bookedtickets',
            old_name='screen_showing_id',
            new_name='screen_showing',
        ),
        migrations.RenameField(
            model_name='bookedtickets',
            old_name='ticket_type_id',
            new_name='ticket_type',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='contact_details_id',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='guesstransaction',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='guesstransaction',
            old_name='card_details_id',
            new_name='card_details',
        ),
        migrations.RenameField(
            model_name='logintransaction',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='logintransaction',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='logintransaction',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='representative',
            old_name='login_account_id',
            new_name='login_account',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='showings_id',
        ),
        migrations.AddField(
            model_name='showing',
            name='screen',
            field=models.ManyToManyField(to='films.Screen'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(max_length=300),
        ),
    ]
