# Generated by Django 4.0.2 on 2022-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_rating',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
