# Generated by Django 4.0.2 on 2022-05-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_showing_capacity'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='films.showing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='bookings.tickettype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookedTickets',
        ),
    ]
