# Generated by Django 4.0.2 on 2022-05-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_showing_booking_ticket_delete_bookedtickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_cost',
            new_name='cost',
        ),
    ]
