# Generated by Django 4.0.2 on 2022-05-08 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_rename_booking_cost_booking_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintransaction',
            name='club',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logintransaction',
            name='discount_at_purchase',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
