# Generated by Django 4.0.2 on 2022-05-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_account_account_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.carddetails'),
        ),
    ]
