# Generated by Django 4.0.2 on 2022-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_account_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_discount',
            field=models.FloatField(default=0),
        ),
    ]
