# Generated by Django 4.0.2 on 2022-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_account_account_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintransaction',
            name='card_number',
            field=models.CharField(default=4111111111111111, max_length=19),
            preserve_default=False,
        ),
    ]
