# Generated by Django 4.0.2 on 2022-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_logintransaction_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=19),
        ),
    ]
