# Generated by Django 4.0.2 on 2022-05-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_carddetails_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_discount_applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
