# Generated by Django 4.0.2 on 2022-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_discount_cost_booking_is_discount_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_cost',
            field=models.FloatField(default=0),
        ),
    ]
