# Generated by Django 4.0.2 on 2022-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_cancelledbookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledbookings',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
