# Generated by Django 4.0.2 on 2022-05-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_name',
            new_name='name',
        ),
    ]
