# Generated by Django 4.0.2 on 2022-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_club_name_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='landline',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='club',
            name='mobile',
            field=models.IntegerField(max_length=13),
        ),
    ]
