# Generated by Django 4.0.2 on 2022-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_age_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
