# Generated by Django 4.0.2 on 2022-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_club_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='account_number',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
