# Generated by Django 4.0.2 on 2022-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_club_account_number_club_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='account_number',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
