# Generated by Django 4.0.2 on 2022-05-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_club_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
    ]
